"""empty message

Revision ID: 6a508290d255
Revises: b48811ec2b89
Create Date: 2024-12-16 18:37:03.545471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a508290d255'
down_revision: Union[str, None] = 'b48811ec2b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'unique_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1000000, increment=1, minvalue=1000000, cycle=False, cache=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'unique_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1000000, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
