"""empty message

Revision ID: c754d89c63da
Revises: 778f0b493b59
Create Date: 2024-12-16 19:32:55.501567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c754d89c63da'
down_revision: Union[str, None] = '778f0b493b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'id')
    op.add_column('transaction', sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True))
    # op.drop_constraint('transaction_unique_id_key', 'transaction', type_='unique')
    # op.drop_constraint('transaction_unique_id_key1', 'transaction', type_='unique')
    op.drop_column('transaction', 'unique_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('unique_id', sa.INTEGER(), sa.Identity(always=True, start=1000000, increment=1, minvalue=1000000, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))
    op.create_unique_constraint('transaction_unique_id_key1', 'transaction', ['unique_id'])
    op.create_unique_constraint('transaction_unique_id_key', 'transaction', ['unique_id'])
    op.alter_column('transaction', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
