"""empty message

Revision ID: 1eacece9633f
Revises: 1b508a1054bb
Create Date: 2024-12-16 20:12:35.413888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eacece9633f'
down_revision: Union[str, None] = '1b508a1054bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'id')
    op.add_column('transaction', sa.Column('unique_id', sa.Integer(), sa.Sequence(
        'transaction_unique_id_seq',
        start=1000000,
        increment=1,
    ), nullable=False))
    op.add_column('transaction', sa.Column('id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'transaction', ['unique_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_unique_id_key', 'transaction', type_='unique')
    op.alter_column('transaction', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('transaction', 'unique_id')
    # ### end Alembic commands ###
