"""empty message

Revision ID: 47702af84972
Revises: 27d827a73cdd
Create Date: 2024-12-25 20:38:14.372835

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47702af84972'
down_revision: Union[str, None] = '27d827a73cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE category DROP id CASCADE")
    op.add_column(
        'category',
        sa.Column('id', sa.UUID, primary_key=True, server_default=str(uuid.uuid4()))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
