"""empty message

Revision ID: 96da3f392cb5
Revises: aae7353f28fc
Create Date: 2024-10-26 15:20:38.289298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96da3f392cb5'
down_revision: Union[str, None] = 'aae7353f28fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('OWNER', 'ADMIN', name='adminrole').create(op.get_bind())
    op.alter_column('admin', 'role',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('OWNER', 'ADMIN', name='adminrole'),
               existing_nullable=False,
               postgresql_using='role::adminrole')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'role',
               existing_type=postgresql.ENUM('OWNER', 'ADMIN', name='adminrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    sa.Enum('OWNER', 'ADMIN', name='adminrole').drop(op.get_bind())
    # ### end Alembic commands ###
