"""empty message

Revision ID: 778f0b493b59
Revises: e2ae422ce124
Create Date: 2024-12-16 18:49:41.952421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778f0b493b59'
down_revision: Union[str, None] = 'e2ae422ce124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_unique_id_key', 'transaction', type_='unique')
    op.drop_column('transaction', 'unique_id')
    op.add_column('transaction', sa.Column('unique_id', sa.Integer(), sa.Identity(
        always=True,
        start=1000000,
        increment=1,
        minvalue=1000000,
    ), nullable=False, unique=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
