"""empty message

Revision ID: c8ffc0ddc8e2
Revises: c3aee870152f
Create Date: 2024-10-27 12:35:04.362796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ffc0ddc8e2'
down_revision: Union[str, None] = 'c3aee870152f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_game_id_fkey', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'game', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('feedback_order_id_fkey', 'feedback', type_='foreignkey')
    op.drop_constraint('feedback_product_id_fkey', 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'product', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'feedback', 'order', ['order_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('order_product_id_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'product', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('product', sa.Column('auto_purchase_image_url', sa.String(), nullable=True))
    op.drop_constraint('product_category_id_fkey', 'product', type_='foreignkey')
    op.drop_constraint('product_game_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'game', ['game_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_game_id_fkey', 'product', 'game', ['game_id'], ['id'])
    op.create_foreign_key('product_category_id_fkey', 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'auto_purchase_image_url')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('order_product_id_fkey', 'order', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key('feedback_product_id_fkey', 'feedback', 'product', ['product_id'], ['id'])
    op.create_foreign_key('feedback_order_id_fkey', 'feedback', 'order', ['order_id'], ['id'])
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_game_id_fkey', 'category', 'game', ['game_id'], ['id'])
    # ### end Alembic commands ###
