"""empty message

Revision ID: 9cdff55e45e8
Revises: e974f7a3f98e
Create Date: 2024-11-07 17:02:00.333944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cdff55e45e8'
down_revision: Union[str, None] = 'e974f7a3f98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('message_url', sa.String(), nullable=True))
    op.drop_column('feedback', 'message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('feedback', 'message_url')
    # ### end Alembic commands ###
