"""empty message

Revision ID: b48811ec2b89
Revises: a13138fb311d
Create Date: 2024-12-16 18:16:40.617272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48811ec2b89'
down_revision: Union[str, None] = 'a13138fb311d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('unique_id', sa.Integer(), sa.Identity(always=False, start=1000000, increment=1), autoincrement=True, nullable=False))
    op.create_unique_constraint(None, 'transaction', ['unique_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='unique')
    op.drop_column('transaction', 'unique_id')
    # ### end Alembic commands ###
