"""empty message

Revision ID: a13138fb311d
Revises: 9cdff55e45e8
Create Date: 2024-11-17 15:57:28.691641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13138fb311d'
down_revision: Union[str, None] = '9cdff55e45e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('feedback', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('order', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('feedback', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('feedback', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
