"""empty message

Revision ID: cd17f22e81b1
Revises: b19e9cab4619
Create Date: 2024-10-15 19:42:36.938319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd17f22e81b1'
down_revision: Union[str, None] = 'b19e9cab4619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_auto_purchase', sa.Boolean(), nullable=False))
    op.add_column('product', sa.Column('auto_purchase_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'auto_purchase_text')
    op.drop_column('product', 'is_auto_purchase')
    # ### end Alembic commands ###
