"""empty message

Revision ID: 1b508a1054bb
Revises: 9e57e63344d3
Create Date: 2024-12-16 19:55:01.753452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b508a1054bb'
down_revision: Union[str, None] = '9e57e63344d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('is_successful', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'is_successful')
    # ### end Alembic commands ###
