"""empty message

Revision ID: 9e57e63344d3
Revises: 06908c98a910
Create Date: 2024-12-16 19:46:05.208636

"""
import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.schema.transaction import TransactionType, TransactionCause


# revision identifiers, used by Alembic.
revision: str = '9e57e63344d3'
down_revision: Union[str, None] = '06908c98a910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.execute("DROP TYPE transactiontype CASCADE")
    op.execute("DROP TYPE transactioncause CASCADE")
    op.create_table('transaction',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('type', sa.Enum(TransactionType), nullable=False),
        sa.Column('cause', sa.Enum(TransactionCause), nullable=False),
        sa.Column('time', sa.TIMESTAMP(timezone=True), nullable=False, default=datetime.datetime.now()),
        sa.Column('amount', sa.DECIMAL(), nullable=False),
        sa.Column('payment_data', sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
