"""empty message

Revision ID: d93687021cce
Revises: e7f7ead8752f
Create Date: 2025-07-18 14:44:21.748610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93687021cce'
down_revision: Union[str, None] = 'e7f7ead8752f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stars', 'id')
    op.add_column('stars', sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stars', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
