"""empty message

Revision ID: e7f7ead8752f
Revises: a13138fb311d
Create Date: 2025-07-18 14:04:09.328605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f7ead8752f'
down_revision: Union[str, None] = '4a50f3fbce28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rate', sa.DECIMAL(), nullable=False),
    sa.Column('api_hash', sa.String(), nullable=False),
    sa.Column('api_cookie', sa.String(), nullable=False),
    sa.Column('mnemonic', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stars')
    # ### end Alembic commands ###
