"""empty message

Revision ID: 59ec545a5570
Revises: d93687021cce
Create Date: 2025-07-20 14:44:42.321975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ec545a5570'
down_revision: Union[str, None] = 'd93687021cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE game_id_seqq START 7 INCREMENT 1")
    
    op.alter_column('game', 'id', 
                   server_default=sa.text("nextval('game_id_seqq')"))
    
    op.execute("ALTER SEQUENCE game_id_seqq OWNED BY game.id")


def downgrade():
    op.alter_column('game', 'id', server_default=None)
    op.execute("DROP SEQUENCE IF EXISTS game_id_seqq")
