"""empty message

Revision ID: 63104a2fdaa8
Revises: c8ffc0ddc8e2
Create Date: 2024-10-27 13:17:24.873912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63104a2fdaa8'
down_revision: Union[str, None] = 'c8ffc0ddc8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_gift_purchase', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_gift_purchase')
    # ### end Alembic commands ###
