"""empty message

Revision ID: 7bfabdffe72e
Revises: 63104a2fdaa8
Create Date: 2024-10-29 16:54:19.951789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bfabdffe72e'
down_revision: Union[str, None] = '63104a2fdaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('admin_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'admin_id')
    # ### end Alembic commands ###
