"""empty message

Revision ID: 499cdfc99a6a
Revises: 91cfb5a12f92
Create Date: 2024-10-25 16:29:47.723136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499cdfc99a6a'
down_revision: Union[str, None] = '91cfb5a12f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('cancel_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'cancel_reason')
    # ### end Alembic commands ###
