"""empty message

Revision ID: c3aee870152f
Revises: 72371f483380
Create Date: 2024-10-26 20:50:51.517259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3aee870152f'
down_revision: Union[str, None] = '72371f483380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_visible', sa.Boolean(), nullable=False, server_default="true"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_visible')
    # ### end Alembic commands ###
