"""empty message

Revision ID: e4498cd49dba
Revises: 499cdfc99a6a
Create Date: 2024-10-25 16:53:47.025076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4498cd49dba'
down_revision: Union[str, None] = '499cdfc99a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('instruction_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'instruction_image_url')
    # ### end Alembic commands ###
